language: node_js
services:
- mongodb
env:
- TEST_MONGO_URL=mongodb://127.0.0.1/admin-bro-mongoose NODE_ENV=test
node_js:
- '8'
script:
- yarn run lint
- yarn test
deploy:
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: HQk1uaTEXD9q0pFwjJfjjx3QPgKmIe4lGN2Y750MCQHCTTR4Oq+ILy2O4twI4v1CEJKBejjaV66X1hfb29dKwZne+0NtPnjPvpRHSllSZI8P4gfLhM2mz4RremMteCUeP1CmUE7jdw1EdlpSZBONA2HMjowzCTHPBlIplh+LDDtekyctDd8tUwNE3LizazX1CgSASwpkB4ZuU9BFmZ8qPwgoe0vy4h6bDINCYwkXS4fVA+bryu3yNSkCU4QbJfxE2Tg6nrPqloVlcgF7BEq4G3CVQoQq7QQWmte1U4Ctb4mpBZf08jiB8OQ7y09idCZPLhd2vTsOckAlBaL+q1jA3wkw0aPmawD/Rj+XBCUUUjUpJTK9dM7ejUqUvg4i6npqnnV90T5MTc/wNRB+as76kfcEMVJbQVcHweJ4IgLCiwPRJforHbw6CK3+pW8cb3Kzn4UZ0prU0m6IDiLt97BZRfRJftxrDNkvVYCfdEcUOZK3P8vwv9gLfyHf/2R/rJzsyDdqkHXGS7UflDWx1Ac2Z4eHpSy/DCo17r8+UlZ5n7qYops31neY49LXeNuDRi0QJJF7luQGyh4UXs4zMGOV8xBby0gXCF4cp91ANFFNAi/dkZsBSAZ34Ny/pJOL+hkilwxi2k7b2y2HrFDHPPo6ZKfAJzrhnLbP/B3p27Glq2w=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-mongoose
notifications:
  slack:
    secure: Z7J5Z6ATkg8PK5dd5F8nXuaj8FytYSVrDRUG4Qc7CafABLwnh56ogGq2I2y15lzwVRk627gv9oNg2T8DnZTcMzupCrRVQ68X4qP9QQ3KARxcPEwuYsazCWggQ6UNEkxDaVvKwLPosMni1HqpVwhReC9zcYfnGpz2A7mMsSSS9XNzynKzAl3zRzs8GMsmlHCZlN3KAY3ejKUavqsMxbkGIV5lyywqKjXrEDZclKSogsYxsci6AY6vYrzznr/BFC8tS5NCQE6McowN3bhKsPTfRrz58OUABOns0N4eEXpdMrNmpro8i6V5KQ7o+7pbplBcUuXMXApKYCnLewcEsF0S4lC8H1KzxOz/haquj5FTz6MLv6uSjCBgvu+ziCNnh1ZH3GFnhA0d9xg7WbbnFJg5fi3rWQQXEP830Oy3XYeCJXKYAuiskx+H6xR0ZzenRvmw9AvjtA2XDh/CsIzmE/+yXaJSIi1mrdr8xwkedIsKmNz7MJeZlTKHxq6JXdV2ADpLylT0eoutzjdfsecM+3aYFmla4WjVuhVnBJRNfmnm7qfqcV9COr0OE7pbpFi5zdrHJKrEf4/92xZ644vE5ifSvri6plANbROUITlBd2sKXUStqj2+c7BnaTmDd64PlNM3JQ87OpibGz6hc5xx6p+j85vUxveysQmnqi6B5VCLD5c=
